Merge front-end with back-end and added error handling
codeforsanjose/litter.ai pull request #17
Opened 2023-12-14 22:40 UTC by B-Tanonaka

1. Closing previous PR about Profile page as this PR has all of the same changes.
2. Connected the leaderboard and profile to the backend so that all data is sourced from the database.
3. Leaderboard and profile change based on if a user is logged in.
4. Created base structure of the login page which enables users to log in and log out.
5. Created an error landing page for all undefined routes. 
6. Some backend changes regarding the data sent back when querying the /photo endpoint are included in this PR to allow the profile page to work.

Jest tests still need to be written for the Profile and PageNotFound components.

2023-12-15 01:35 UTC, JMStudiosJoe commented
is this pr relying on #16 ?

2023-12-15 01:36 UTC, JMStudiosJoe commented
do i merge 16 first or can this just be merged?

2023-12-15 01:49 UTC, JMStudiosJoe requested changes
if any of my comments are from previous pr please respond to the comment saying so and dont fix.

2023-12-15 01:49 UTC, JMStudiosJoe commented on client/src/utils/capitalizeFirstLetter.js
> +export const capitalizeList = (list) => (
is this for backend or for UI? for web UI this should be done in just CSS. However I know in React-native they dont but this aint react-native, yet.

2023-12-15 01:49 UTC, JMStudiosJoe commented on client/src/utils/capitalizeFirstLetter.js
> +export const capitalizeList = (list) => (
if this is just for web and just for the UI then lets keep it as CSS `text-decoration: 'capitolize'`  or something like that

2023-12-15 01:49 UTC, JMStudiosJoe commented on client/src/utils/FetchUserData.js
> +    const res = await fetch(URLpath('login'), {
I do like how this is one of the few places we are using fetch, great job on that. Id say lets take it a step further, make its own utils file where `fetch` is only used there. That way if need to use something else, we only have one place to change it. Does that make sense?

2023-12-15 01:49 UTC, JMStudiosJoe commented on client/src/Components/Register/Login.jsx
> +
Components/Register/Login.jsx ? why is login within Register?

2023-12-15 01:49 UTC, JMStudiosJoe commented on client/src/Components/Register/Login.jsx
> +
if this is apart of previous pr my bad.

2023-12-15 01:49 UTC, JMStudiosJoe commented on client/src/Components/Profile/ProfileStatistics.jsx
> +  useEffect(() => {
ah, yes please do with css class. CSS is much much faster than js and we can almost count all the steps js will go through. CSS is always better in web for how the UI should be displayed, and also is way faster in animtions last i checked.

2023-12-15 20:04 UTC, B-Tanonaka commented
> is this pr relying on #16 ?

Yes these backend changes are in #16. Tim said he made the changes you requested in #16 and I pulled them into this branch.

2023-12-15 23:26 UTC, B-Tanonaka commented
@JMStudiosJoe The requested changes have been pushed. Thank you for the feedback.

2023-12-16 00:27 UTC, JMStudiosJoe commented
just merged pr #16 please pull the latest changes and update this pr and it should be a lot less changes and clean :) and then ready for merge. GREAT WORK!!!

2023-12-16 00:41 UTC, B-Tanonaka commented
Just pulled the changes from main. This should be ready to merge now.

2023-12-19 17:35 UTC, merged